import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Cursor from '@/_components/Cursor'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=" ">
      <body className={`${inter.className} bg-[#0c0c1d] text-gray-300 `}>
        <Cursor />
        {children}
      </body>
    </html>
  )
}
